### ISSUE TITLE
`build-ami.py` fails at `pip install -r requirements.txt` step in apply_manifests()

### ISSUE THREAD

**Issue by toffer** [toffer/minecloud-ami#8]
I first noticed this error after the release of pip v. 1.4.

Here's the relevant issue on the pip issue tracker:
- https://github.com/pypa/pip/issues/1074

Here's the debug info:

```
debug: Exec[pip-install-requirements](provider=posix): Executing '/usr/local/venv/bin/pip install -r /usr/local/venv/requirements.txt'
debug: Executing '/usr/local/venv/bin/pip install -r /usr/local/venv/requirements.txt'
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns: Traceback (most recent call last):
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns:   File "/usr/local/venv/bin/pip", line 9, in <module>
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns:     load_entry_point('pip==1.4', 'console_scripts', 'pip')()
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns:   File "/usr/local/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns:     return get_distribution(dist).load_entry_point(group, name)
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns:   File "/usr/local/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns:     return ep.load()
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns:   File "/usr/local/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns:     entry = __import__(self.module_name, globals(),globals(), ['__name__'])
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns:   File "/usr/local/venv/local/lib/python2.7/site-packages/pip/__init__.py", line 11, in <module>
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns:     from pip.vcs import git, mercurial, subversion, bazaar  # noqa
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns:   File "/usr/local/venv/local/lib/python2.7/site-packages/pip/vcs/subversion.py", line 4, in <module>
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns:     from pip.index import Link
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns:   File "/usr/local/venv/local/lib/python2.7/site-packages/pip/index.py", line 32, in <module>
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns:     from pip.wheel import Wheel, wheel_ext, wheel_setuptools_support, setuptools_requirement
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns:   File "/usr/local/venv/local/lib/python2.7/site-packages/pip/wheel.py", line 18, in <module>
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns:     from pip import pep425tags
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns:   File "/usr/local/venv/local/lib/python2.7/site-packages/pip/pep425tags.py", line 98, in <module>
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns:     supported_tags = get_supported()
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns:   File "/usr/local/venv/local/lib/python2.7/site-packages/pip/pep425tags.py", line 61, in get_supported
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns:     soabi = sysconfig.get_config_var('SOABI')
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns:   File "/usr/lib/python2.7/sysconfig.py", line 577, in get_config_var
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns:     return get_config_vars().get(name)
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns:   File "/usr/lib/python2.7/sysconfig.py", line 476, in get_config_vars
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns:     _init_posix(_CONFIG_VARS)
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns:   File "/usr/lib/python2.7/sysconfig.py", line 344, in _init_posix
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns:     raise IOError(msg)
notice: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns: IOError: invalid Python installation: unable to open /usr/venv/lib/python2.7/config/Makefile (No such file or directory)
err: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns: change from notrun to 0 failed: /usr/local/venv/bin/pip install -v -r /usr/local/venv/requirements.txt returned 1 instead of one of [0] at /home/ubuntu/puppet-minecraft/modules/virtualenv/manifests/init.pp:44
```

**Comment by toffer** [comment]
Previous commit (https://github.com/toffer/minecloud-ami/commit/90eeeab15cfcaae92dab1c57d903cc3a9cca863c) provides a temporary fix.

Leaving issue open until an update to pip (https://github.com/pypa/pip) fixes the issue for real.

**Comment by verveguy** [comment]
The upstream issue now appears to be fixed.
